# {\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Night Rider",
  "postType": "post",
  "slug": "night-rider",
  "status": "draft",
  "content": "post-content",
  "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  // "publishOn": "2024-03-19T07:46:32+0000",
  "metaOptions": {
"metaValue":"{\"sideBarEnabled\":true, \"footerActive\":true}"
},
"tags":["2951c2f1-4a76-4ef4-a9f1-cf58e5427ea5"],
"authorId":"da9ec316-9a4c-49e9-b326-b4e04a110c50"
}