
POST http://localhost:3000/users
Content-Type:application/json
{
    "firstName":"Irtaza",
    "lastName":"Matric",
    "email":"irtazamatic@gmail.com",
    "password":"Abcde123#"
}


POST http://localhost:3000/users/create-many
Content-Type:application/json
{
    "users":[{
    "firstName":"Under",
    "lastName":"Taker",
    "email":"undertaker000@gmail.com",
    "password":"Abcde123#"
},
{
    "firstName":"John",
    "lastName":"Cena",
    "email":"johncena2024@gmail.com",
    "password":"Abcde123#"
}]
}